CREATE TABLE pauta
(
    id        NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo    VARCHAR(255) NOT NULL,
    descricao VARCHAR(500)
);

CREATE TABLE sessao_votacao
(
    id              NUMBER(19, 0) PRIMARY KEY,
    pauta_id         NUMBER(19, 0),
    data_abertura   TIMESTAMP NOT NULL,
    data_fechamento TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pauta (id)
);

CREATE TABLE voto
(
    id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id      NUMBER(19, 0) NOT NULL,
    associado_id  VARCHAR2(255) NOT NULL,
    escolha      VARCHAR2(10)  NOT NULL,
    CONSTRAINT fk_voto_pauta FOREIGN KEY (pauta_id) REFERENCES pauta (id),
    CONSTRAINT uk_voto_associado_pauta UNIQUE (pauta_id, associado_id)
);
